--- # Collecting System info
- hosts: centos
  tasks:
    - name: Kernel
      debug: msg="{{ ansible_kernel }}"
    - name: Hostname
      debug: msg="{{ ansible_hostname }}"
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - debug: var=ansible_architecture
    - debug: var=inventory_hostname
    - debug: var=groups
    - debug: var=group_names
    - name: print IPv4 Address
      debug:
        msg: "IPv4 address: {{ ansible_default_ipv4.address }}"
    # - debug: var=hostvars
