--- # Conditional Based PlayBook
-  hosts: webserver
   remote_user: ansible
   become: yes
   become_method: sudo
   connection: ssh
   gather_facts: yes
   tasks:
   - name: If Os is RedHat install Http
     yum:
         name: git
         state: present
     when: ansible_os_family == 'RedHat'
   - name: If Os is RedHat install Http
     apt:
         name: git
         state: present
     when: ansible_os_family == 'Ubuntu'

- hosts: all
  vars:
    - create_user_file: yes
    - user: ansible
  tasks:
    - name: create file for user
      file:
        path: /home/{{ user }}/myfile
        state: absent
      when: create_user_file

